version: "3"

services: 
    db:
        image: mongo:4.4.5
        environment: 
            - PUID=1000
            - PGID=1000
        volumes:
            - ./mongo_data:/data/db
        ports:
            - "27017:27017"

    web_dev:
        build: .
        depends_on:
            - db
        ports: 
            - "5000:5000"